const kICON_SIZE_LETTER_HOME = 50.0;
const kICON_SIZE_BIG_LETTER_HOME = 80.0;
const kLETTER_ICON_SIZE_LETTER_HOME = 70.0;
const kLETTER_ICON_SIZE_LETTER_DESCRIPTION = 120.0;
const kLETTER_SIZE = 50.0;
const kLETTER_CONTAINER_WIDTH = 80.0;
const kLETTER_CONTAINER_Hight = 150.0;
